apiVersion: v1
kind: ServiceAccount
metadata:
  name: dink
  namespace: dink
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dink
subjects:
  - kind: ServiceAccount
    name: dink
    namespace: dink
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: dink-server
  namespace: dink
spec:
  selector:
    app: dink
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dink
  namespace: dink
spec:
  selector:
    matchLabels:
      app: dink
  template:
    metadata:
      labels:
        app: dink
    spec:
      serviceAccountName: dink
      containers:
        - name: dinkd
          image: arvintian/dink-bundle:eec45f2
          ports:
            - containerPort: 8000
              name: http
          command:
            - /app/play
            - --agent-image
            - arvintian/dink-bundle:eec45f2
            - --nfs-server
            - dink.nfs.address
            - --nfs-path
            - /share/dink
            - --docker-host
            - tcp://dink-dind:2375
          volumeMounts:
            - name: dink-root
              mountPath: /var/lib/dink
      volumes:
        - name: dink-root
          persistentVolumeClaim:
            claimName: dink-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dink-dind
  namespace: dink
spec:
  selector:
    app: dink-dind
  ports:
    - port: 2375
      targetPort: 2375
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dink-dind
  namespace: dink
spec:
  selector:
    matchLabels:
      app: dink-dind
  template:
    metadata:
      labels:
        app: dink-dind
    spec:
      serviceAccountName: dink
      containers:
        - name: dink-dind
          image: arvintian/dink-dind:eec45f2
          ports:
            - containerPort: 2375
          env:
            - name: DOCKER_HOST
              value: tcp://0.0.0.0:2375
            - name: DOCKER_TLS_CERTDIR
              value: ""
          securityContext:
            privileged: true
          volumeMounts:
            - name: dink-root
              mountPath: /var/lib/docker
              subPath: docker
      volumes:
        - name: dink-root
          persistentVolumeClaim:
            claimName: dink-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dink-pvc
  namespace: dink
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  volumeName: dink-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dink-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  nfs:
    server: dink.nfs.address
    path: /share/dink
  mountOptions:
    - vers=3
    - timeo=600
    - retrans=10
    - intr
    - nolock
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem